language: go
go:
  - "1.13.x"

env:
  global:
    - CGO_ENABLED=0
    - GOOS=linux
    - GOARCH=amd64

services:
  - docker

script:
  - go build -ldflags="-s -w" -installsuffix cgo -o hotlist_server .
  - docker build -t guygubaby/hotlist-server-golang:latest .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push guygubaby/hotlist-server-golang:latest

notifications:
  email:
    recipients:
      - 1907004005@qq.com
    on_success: change
    on_failure: always
