language: go
go:
  - "1.13.x"

env:
  global:
    - GOOS=linux
    - GOARCH=amd64

services:
  - docker

before_install:
  - go build -o hotlist_server .

install:
  - docker build -t guygubaby/hotlist-server-golang:latest .

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push guygubaby/hotlist-server-golang:latest

notifications:
  email:
    recipients:
      - 1907004005@qq.com
    on_success: change
    on_failure: always
